### ISSUE TITLE
Unable to use `resize-mode` in `neo-tree`

### ISSUE THREAD

**Issue by SimonBrandner** [Dimfred/resize-mode.nvim#4]
When I am in `neo-tree` the `resize-mode` binds do not take precedence and I unable to escape the mode

**Comment by Dimfred** [comment]
Hmm interesting. Sry I don't use neo-tree so no clue, feel free to debug it and submit a PR, I am a little short on time the next weeks.

**Comment by SimonBrandner** [comment]
New to NeoVim, so it might take a while before I am able to do that... Wonder if https://github.com/Iron-E/nvim-libmodal could help

**Comment by Dimfred** [comment]
I just tried it and I have a feeling for why this is happening. So resize mode, creates tmp keymappings when it is enabled. I think somehow those get overwritten by Neotree.

EDIT:
So I stole most of the stuff from here anyways https://github.com/mrjones2014/smart-splits.nvim I didn't need alot of stuff in that plugin so I didn't want to use it. But really liked the resize mode. Maybe you try his plugin, I would assume that this one is way more stable than mine.

**Comment by Dimfred** [comment]
Closing this as not going to fix that since I don't use neotree
