### ISSUE TITLE
Indicate in the UI that the resize mode is active

### ISSUE THREAD

**Issue by SimonBrandner** [Dimfred/resize-mode.nvim#5]
Perhaps https://github.com/Iron-E/nvim-libmodal could help

**Comment by Dimfred** [comment]
Mhh, sry dunno what you mean by that? Do you mean that you would like to have an indicator that the resize mode is active?

If so, you can create your own indicator for `on_enter` and `on_leave`.

**Comment by SimonBrandner** [comment]
Yep, that is what I meant. It took me a while to figure out [a hack](https://github.com/SimonBrandner/dotfiles/commit/31e5800e0c35f1c36a929316b2d237767a6895a4) to do it as someone who just started learning NeoVim... Perhaps an integration with something like https://github.com/Iron-E/nvim-libmodal would help

**Comment by Dimfred** [comment]
That's not a hack that literally what the functions are for. To do whatever you need :)
Don't really see the integration with a modal plugin, I personally don't care about a modal and don't need that. And yeah again thats what the hooks are for. I don't want to force anything on anyone, everyone just integrates as he pleases.

**Comment by SimonBrandner** [comment]
Fair
